#
# Configuration file for generateInjectionCatalogForField script.
#

[FAKE_SOURCES_CATALOG]
inject_fake_sinusoidal_variables = True
num_sinusoidal_variables = 50
sinusoidal_period_min = 0.1
sinusoidal_period_max = 1000.0
sinusoidal_amplitude_min = 0.01
sinusoidal_amplitude_max = 2.0
sinusoidal_magnitude_min = 21.0
sinusoidal_magnitude_max = 28.0
sinusoidal_phase_min = 0.0
sinusoidal_phase_max = 1.0
inject_fake_gaussian_variables = True
num_gaussian_variables = 50
gaussian_peak_time_min = 61800.0
gaussian_peak_time_max = 62800.0
gaussian_amplitude_min = 0.1
gaussian_amplitude_max = 5.0
gaussian_sigma_min = 1.0
gaussian_sigma_max = 300.0
gaussian_magnitude_min = 21.0
gaussian_magnitude_max = 28.0
