FROM redhat/ubi9

RUN yum install -y pip

RUN pip install numpy
RUN pip install astropy
RUN pip install psycopg2-binary
RUN pip install opencv-python-headless
RUN pip install pytest
RUN pip install healpy

RUN yum -y install gcc
RUN yum -y install g++
RUN yum -y install gfortran
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool
RUN yum -y install zlib-devel
RUN yum -y install atlas
RUN yum -y install atlas-devel


RUN yum -y install cmake
RUN yum -y install wget
RUN yum -y install git

# Install Boost library under /usr/local (needed by SourceXtractorPlusPlus).
# There is not enough space on an EC2 instance with an 8-GByte boot disk
# to build the boost library, which is needed for SExtractorPlusPlus.
# Also, machine memory of at least 4 GB is required.

RUN cd /tmp && \
    wget https://boostorg.jfrog.io/artifactory/main/release/1.85.0/source/boost_1_85_0.tar.gz && \
    gunzip boost_1_85_0.tar.gz && \
    tar -xvf boost_1_85_0.tar && \
    cd boost_1_85_0 && \
    ./bootstrap.sh --prefix=/usr/local && \
    ./b2 install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install log4cpp library under /usr/local (needed by SourceXtractorPlusPlus).

RUN cd /tmp && \
    wget https://sourceforge.net/projects/log4cpp/files/latest/download/log4cpp-1.1.4.tar.gz && \
    gunzip  log4cpp-1.1.4.tar.gz && \
    tar -xvf log4cpp-1.1.4.tar && \
    cd log4cpp && \
    ./configure && \
    make && \
    make check && \
    make install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install gmock and gtest libraries under /usr/local/lib64 (needed by SourceXtractorPlusPlus).

RUN cd /tmp && \
    git clone https://github.com/google/googletest.git -b v1.14.0 && \
    cd googletest && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-fPIE" .. && \
    make && \
    make install && \
    cd /tmp && \
    rm -rf /tmp/*


# Install xz and diff commands.  Needed for diagnosing build problems.

RUN dnf -y install xz

RUN cd /tmp && \
    curl --silent --output diffutils-3.10.tar.xz ftp://ftp.gnu.org/gnu/diffutils/diffutils-3.10.tar.xz && \
    tar -xf diffutils-3.10.tar.xz && \
    cd diffutils-3.10 && \
    ./configure --prefix=/usr && \
    make install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install Elements library in /usr/local/lib64  (needed by SourceXtractorPlusPlus).
# Some of the C++ programs need to updated for the new interface in the latest version of boost/filesystem.

RUN cd /tmp && \
    wget -O Elements-6.1.4.tar.gz https://github.com/astrorama/Elements/archive/refs/tags/6.1.4.tar.gz && \
    gunzip Elements-6.1.4.tar.gz && \
    tar -xvf Elements-6.1.4.tar && \
    cd Elements-6.1.4 && \
    mkdir build && \
    cd build  && \
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCFITSIO_LIBRARY=/code/c/lib/libcfitsio.a \
          -DCFITSIO_INCLUDE_DIR=/code/c/include/cfitsio \
          -DWCSLIB_LIBRARY=/code/c/lib/libwcs.a -DWCSLIB_INCLUDE_DIR=/code/c/include/wcslib \
          -DGSL_LIBRARY=/code/c/lib/libgsl.a -DGSL_CBLAS_LIBRARY=/code/c/lib/libgslcblas.a -DGSL_INCLUDE_DIR=/code/c/include \
          -DPYTHON_LIBRARY=/usr/lib/python3.9 -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 \
          -DPYTHON_EXPLICIT_VERSION=3 -DUSE_SPHINX=OFF .. && \
    perl -e '@op=`cat /tmp/Elements-6.1.4/ElementsKernel/src/Lib/ProgramManager.cpp`; foreach $op (@op) { if ($op =~/complete/) { $op =~ s/complete/absolute/;}  print "$op"; }' > save1.tmp && \
    /usr/bin/cp -f save1.tmp /tmp/Elements-6.1.4/ElementsKernel/src/Lib/ProgramManager.cpp && \
    perl -e '@op=`cat /tmp/Elements-6.1.4/ElementsKernel/tests/src/Path_test.cpp`; foreach $op (@op) { if ($op =~/regular;/) { $op =~ s/is_regular;/is_regular_file;/;}  print "$op"; }' > save2.tmp && \
    /usr/bin/cp -f save2.tmp /tmp/Elements-6.1.4/ElementsKernel/tests/src/Path_test.cpp && \
    perl -e '@op=`cat /tmp/Elements-6.1.4/ElementsKernel/tests/src/Configuration_test.cpp`; foreach $op (@op) { if ($op =~/regular;/) { $op =~ s/is_regular;/is_regular_file;/;}  print "$op"; }' > save3.tmp && \
    /usr/bin/cp -f save3.tmp /tmp/Elements-6.1.4/ElementsKernel/tests/src/Configuration_test.cpp && \
    perl -e '@op=`cat /tmp/Elements-6.1.4/ElementsKernel/tests/src/Auxiliary_test.cpp`; foreach $op (@op) { if ($op =~/regular;/) { $op =~ s/is_regular;/is_regular_file;/;}  print "$op"; }' > save4.tmp && \
    /usr/bin/cp -f save4.tmp /tmp/Elements-6.1.4/ElementsKernel/tests/src/Auxiliary_test.cpp && \
    make  && \
    make install && \
    cd /tmp && \
    rm -rf /tmp/*
