FROM redhat/ubi9

# Install commands and tools.

RUN yum -y install gcc
RUN yum -y install g++
RUN yum -y install gfortran
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool
RUN yum -y install zlib-devel
RUN yum -y install atlas
RUN yum -y install atlas-devel
RUN yum -y install postgresql
RUN yum -y install unzip
RUN yum -y install git
RUN yum -y install sqlite
RUN yum -y install diffutils
RUN yum -y install which
RUN yum -y install file

# Remove requests from RPM package to allow
# romanisim to install under Python 3.9

RUN yum -y remove python3-requests

# Install packages in Python 3.9 (/usr/bin/python3)

RUN yum install -y pip
RUN pip install --upgrade pip
RUN pip install --upgrade numpy
RUN pip install --upgrade astropy
RUN pip install --upgrade pandas
RUN pip install --upgrade psycopg2-binary
RUN pip install --upgrade healpy
RUN pip install --upgrade boto3
RUN pip install --upgrade --ignore-installed pyfftw
RUN pip install --upgrade sympy
RUN pip install --upgrade sip_tpv
RUN pip install --upgrade photutils
RUN pip install --upgrade matplotlib
RUN pip install --upgrade galsim
RUN pip install --upgrade romanisim
RUN pip install --upgrade scikit-image

# Set up separate Python 3.9 venv under root directory for sfft.

RUN python3 -m venv /sfft_env
RUN source /sfft_env/bin/activate
RUN python3 -m pip install --upgrade sfft
RUN deactivate

# Install Python 3.11 with packages (/usr/bin/python3.11)

RUN dnf -y install python3.11
RUN python3.11 -m ensurepip
RUN python3.11 -m pip install --upgrade pip
RUN python3.11 -m pip install --upgrade numpy
RUN python3.11 -m pip install --upgrade astropy
RUN python3.11 -m pip install --upgrade pandas
RUN python3.11 -m pip install --upgrade psycopg2-binary
RUN python3.11 -m pip install --upgrade healpy
RUN python3.11 -m pip install --upgrade boto3
RUN python3.11 -m pip install --upgrade pyfftw
RUN python3.11 -m pip install --upgrade sympy
RUN python3.11 -m pip install --upgrade sip_tpv
RUN python3.11 -m pip install --upgrade photutils
RUN python3.11 -m pip install --upgrade matplotlib
RUN python3.11 -m pip install --upgrade galsim
RUN python3.11 -m pip install --upgrade romanisim
RUN python3.11 -m pip install --upgrade scikit-image


# Cannot install sfft in Python 3.11 because of following error:
# Failed to build scikit-image
# ERROR: Failed to build installable wheels for some pyproject.toml based projects (scikit-image)
# The command '/bin/sh -c python3.11 -m pip install --upgrade sfft' returned a non-zero code: 1
# For now, the plan is to run sfft under Python 3.9

#RUN python3.11 -m pip install --upgrade sfft


# Install AWS CLI

RUN cd /tmp && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install ps command.

RUN yum -y install procps

# Checkout RAPID git repo.

RUN git clone https://github.com/Caltech-IPAC/rapid code
WORKDIR /code

# Build C code in RAPID software stack.

ARG RAPID_SW=/code
RUN cd /code/c/builds && \
    ./build_inside_container.sh

# Configure run-time environment.

ENV PATH=/code/c/bin:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LD_LIBRARY_PATH=/code/c/lib
ENV PYTHONPATH=/code
ENV PYTHONUNBUFFERED=1

WORKDIR /tmp

# Make the entrypoint bash so arbitrary commands can override the default.

ENTRYPOINT ["bash"]

CMD ["/code/pipeline/awsBatchSubmitJobs_runSingleSciencePipeline.sh"]
