FROM redhat/ubi9

# The docker build command for this Dockerfile is executed on an Ubuntu machine.
# The entrypoint for the resulting docker image is a command to execute awsBatchJobLowLevelScript_CompressTroxelFitsFiles.py

RUN yum install -y pip

RUN pip install --upgrade numpy
RUN pip install --upgrade astropy
RUN pip install --upgrade psycopg2-binary
RUN pip install healpy
RUN pip install boto3

RUN yum -y install gcc
RUN yum -y install g++
RUN yum -y install gfortran
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool
RUN yum -y install zlib-devel
RUN yum -y install atlas
RUN yum -y install atlas-devel
RUN yum -y install postgresql
RUN yum -y install unzip

# Install AWS CLI

RUN cd /tmp && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install ps command.

RUN yum -y install procps

# Run python3 and pass script name and optional parameter(s).

ENTRYPOINT ["/usr/bin/python3"]
CMD ["/code/test.py","Hello World!"]
