FROM redhat/ubi9

RUN yum install -y pip

RUN pip install --upgrade numpy
RUN pip install --upgrade astropy
RUN pip install --upgrade psycopg2-binary
RUN pip install healpy
RUN pip install boto3

RUN yum -y install gcc
RUN yum -y install g++
RUN yum -y install gfortran
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool
RUN yum -y install zlib-devel
RUN yum -y install atlas
RUN yum -y install atlas-devel
RUN yum -y install postgresql
RUN yum -y install unzip

# Install AWS CLI

RUN cd /tmp && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    cd /tmp && \
    rm -rf /tmp/*

# Install ps command.

RUN yum -y install procps

# Add and run script called fetch_and_run.sh located in docker subdirectory in RAPID git repo.
# You must build docker image from top-level rapid directory.

ADD docker/fetch_and_run.sh /usr/local/bin/fetch_and_run.sh

# Add python script called awsBatchJobLowLevelScript_CompressTroxelFitsFiles.py located in sims/src/ subdirectory in RAPID git repo.

ADD sims/src/awsBatchJobLowLevelScript_CompressTroxelFitsFiles.py /usr/local/bin/awsBatchJobLowLevelScript_CompressTroxelFitsFiles.py

WORKDIR /tmp

ENTRYPOINT ["/usr/local/bin/fetch_and_run.sh"]