FROM redhat/ubi9

RUN yum install -y pip

RUN pip install --upgrade numpy
RUN pip install --upgrade astropy
RUN pip install --upgrade psycopg2-binary
RUN pip install healpy

RUN yum -y install gcc
RUN yum -y install g++
RUN yum -y install gfortran
RUN yum -y install autoconf
RUN yum -y install automake
RUN yum -y install libtool
RUN yum -y install zlib-devel
RUN yum -y install atlas
RUN yum -y install atlas-devel
RUN yum -y install postgresql
