"""
Generate RST tables for the alert schema from alerts/param_registry.py.

Called by conf.py at the start of every Sphinx build; writes
prod/alert_params.inc (git-ignored), which products.rst pulls in with an
``.. include::`` directive. This keeps the documented schema in lockstep
with the registry -- do not edit the generated file by hand.

Can also be run standalone for a quick look at the output:

    python docs/source/gen_alert_params.py
"""

import sys
from pathlib import Path

DOCS_SOURCE = Path(__file__).resolve().parent
REPO_ROOT = DOCS_SOURCE.parents[1]
OUTPUT = DOCS_SOURCE / "prod" / "alert_params.inc"

sys.path.insert(0, str(REPO_ROOT))

from alerts.param_registry import RECORDS, VERSION, Status  # noqa: E402

STATUS_LABEL = {
    Status.IMPLEMENTED: "**Implemented**",
    Status.STUB: "STUB",
    Status.NOT_USED: "*not used*",
}


def format_avro(avro) -> str:
    """Render a version-independent Avro type spec as a short string."""
    if isinstance(avro, str):
        return avro.lstrip("@")
    if isinstance(avro, dict):
        return f"array<{format_avro(avro['items'])}>"
    if isinstance(avro, list):
        return " | ".join(format_avro(t) for t in avro)
    return str(avro)


def record_section(record) -> list[str]:
    """Build the RST lines for one record: heading, counts, param table."""
    counts = {status: sum(1 for p in record.params if p.status is status)
              for status in Status}
    summary = (f"{len(record.params)} params: "
               f"{counts[Status.IMPLEMENTED]} implemented, "
               f"{counts[Status.STUB]} stub")
    if counts[Status.NOT_USED]:
        summary += f", {counts[Status.NOT_USED]} not used"

    lines = [
        f"``{record.name}``",
        "-" * (len(record.name) + 4),
        record.doc,
        f"    *{summary}*",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 18 14 12 34 26",
        "",
        "   * - Parameter",
        "     - Avro type",
        "     - Status",
        "     - Description",
        "     - Source",
    ]
    for p in record.params:
        source = f"``{p.source}``" if p.source else ""
        lines += [
            f"   * - ``{p.name}``",
            f"     - ``{format_avro(p.avro)}``",
            f"     - {STATUS_LABEL[p.status]}",
            f"     - {p.doc}",
            f"     - {source}",
        ]
    lines.append("")
    return lines


def write_alert_params(outfile: Path = OUTPUT) -> None:
    """Write the generated RST fragment for all alert schema records."""
    lines = [
        ".. AUTO-GENERATED by docs/source/gen_alert_params.py from",
        "   alerts/param_registry.py at build time -- DO NOT EDIT.",
        "",
        f"The current alert schema version is ``{VERSION}``. The tables below",
        "are generated directly from ``alerts/param_registry.py``, the schema builder,"
        " and reflect its state at the time",
        "these docs were built. Statuses:",
        "",
        "- **Implemented**: The value is populated from the pipeline in",
        "  produced alerts.",
        "- **Stub**: The field is present in the schema but always serialized",
        "  as null; the *Source* column notes what upstream piece is still",
        "  needed.",
        "- **Not used**: Declared in the registry but currently excluded from",
        "  the schema and from built alert packets entirely.",
        "",
    ]
    for record in RECORDS:
        lines += record_section(record)
    outfile.write_text("\n".join(lines) + "\n")
    print(f"gen_alert_params: wrote {outfile.relative_to(REPO_ROOT)} "
          f"(schema version {VERSION}, {len(RECORDS)} records)")


if __name__ == "__main__":
    write_alert_params()
