-- 011-attempt-records.sql — attempt-record schema (D:attempt-record-schema).
--
-- The attempt record is the authoritative, queryable account of every
-- processing attempt: three live-state tables plus the immutable S3 terminal
-- record (the S3 half is not DDL and ships with the emission code).
--
-- Normative source: rapid_plan design/observability.md § Attempt record, and
-- decisions.md § Attempt-record schema (ADOPTED, Ben 2026-08-03), including
-- BOTH ratified amendments of the same date:
--
--   1. The CHECK set is derived mechanically from the § 4 lifecycle matrix, so
--      every Required and every Absent cell of that matrix is constraint-backed
--      — not merely the subset the original proposal's CHECKs covered.
--   2. Timestamp authorship: `created_at` (logical-job creation) is
--      application-authored, and the scheduler-observed timestamps live in
--      their own reconciler-written columns beside the application-authored
--      ones, plus `scheduler_attempt_index`. No column ever has two writers for
--      the same row, so application-vs-scheduler disagreement is preserved for
--      reconciliation rather than overwritten.
--
-- The amendments' landing rule: they fold directly into this migration because
-- the attempt-record schema has not been applied to any database — one coherent
-- schema, nothing deployed to migrate from.
--
-- Conventions follow the existing stream and the project's DDL decisions:
-- `timestamptz` wall clocks, durations `numeric` with the unit in the column
-- name, legible text vocabularies with CHECK constraints (never integer codes —
-- project decision 2026-08-02; the coded-int pattern in the legacy baseline is
-- not a model to repeat), `GENERATED BY DEFAULT AS IDENTITY` surrogate keys,
-- `IF NOT EXISTS` guards so re-running the applier is a no-op.

-- ---------------------------------------------------------------------------
-- attempts — one row per attempt, updated in place as it advances through the
-- lifecycle states. A retry (scheduler or orchestrator) is a NEW row with its
-- own immutable attempt identity, never an update to a prior attempt.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attempts (
    attempt_id       bigint GENERATED BY DEFAULT AS IDENTITY,
    schema_version   smallint NOT NULL,

    -- Identity (policy: attributability).
    run_id           text NOT NULL,
    logical_job_id   text NOT NULL,
    scheduler_job_id text,              -- Batch job ID; NULL until assigned
    exposure_id      integer,
    sca              smallint,
    sky_tile         text,

    -- Lifecycle.
    lifecycle_state  text NOT NULL,

    -- Outcome: a five-field taxonomy, never one collapsed status.
    scheduler_state     text,
    process_exit_code   integer,
    rapid_outcome       text,
    product_disposition text,
    error_category      text,

    -- Application-authored timestamps (amendment 2). `created_at` is logical-job
    -- creation; `submitted_at` is the moment the submitter issued the
    -- submission, NOT Batch acceptance.
    created_at       timestamptz NOT NULL,
    submitted_at     timestamptz NOT NULL,
    started_at       timestamptz,
    -- `ended_at` is written by whichever party closes the attempt: the job at
    -- clean exit, the reconciler at classification. Still single-writer per row.
    ended_at         timestamptz,

    -- Scheduler-observed timestamps — ALWAYS reconciler-written, from
    -- DescribeJobs, never by the application (amendment 2).
    scheduler_created_at    timestamptz,
    scheduler_started_at    timestamptz,
    scheduler_stopped_at    timestamptz,
    scheduler_attempt_index integer,

    -- Provenance, carried on the started row; the S3 terminal record is
    -- authoritative. The attempt record is the provenance query surface — there
    -- is deliberately no separate registry table.
    source_sha         text,
    container_digest   text,
    job_definition_rev text,
    config_digest      text,

    -- Reconciliation (missing_or_contradictory rows only).
    reconciliation_class       text,
    reconciliation_sources     text[],
    reconciliation_detected_at timestamptz,

    CONSTRAINT attempts_pkey PRIMARY KEY (attempt_id),
    CONSTRAINT attempts_run_job_attempt_uq UNIQUE (run_id, logical_job_id, attempt_id),

    -- Vocabularies.
    CONSTRAINT attempts_lifecycle_state_check CHECK (lifecycle_state IN (
        'submitted', 'started', 'terminal_after_start',
        'terminal_without_start', 'missing_or_contradictory'
    )),
    CONSTRAINT attempts_scheduler_state_check CHECK (scheduler_state IS NULL OR scheduler_state IN (
        'SUBMITTED', 'PENDING', 'RUNNABLE', 'STARTING', 'RUNNING',
        'SUCCEEDED', 'FAILED'
    )),
    CONSTRAINT attempts_rapid_outcome_check CHECK (rapid_outcome IS NULL OR rapid_outcome IN (
        'success', 'failure', 'partial'
    )),
    CONSTRAINT attempts_product_disposition_check CHECK (product_disposition IS NULL OR product_disposition IN (
        'published', 'withheld', 'superseded', 'none'
    )),
    CONSTRAINT attempts_reconciliation_class_check CHECK (reconciliation_class IS NULL OR reconciliation_class IN (
        'missing', 'contradictory'
    )),
    CONSTRAINT attempts_scheduler_attempt_index_check CHECK (
        scheduler_attempt_index IS NULL OR scheduler_attempt_index >= 0
    ),

    -- -----------------------------------------------------------------------
    -- Lifecycle matrix, mechanically derived (amendment 1). One constraint per
    -- state: each names that state's Required cells and its Absent cells, so
    -- every cell of § 4 is backed. Each is written as
    -- `state <> 'x' OR (<required NOT NULL> AND <absent IS NULL>)`, which is
    -- vacuously true for other states — the states are checked independently.
    -- -----------------------------------------------------------------------

    -- Submitted: identity + created_at/submitted_at. scheduler_job_id is
    -- "where known" — nullable here, required from `started` onward.
    CONSTRAINT attempts_state_submitted_check CHECK (
        lifecycle_state <> 'submitted' OR (
            started_at IS NULL
            AND ended_at IS NULL
            AND scheduler_state IS NULL
            AND process_exit_code IS NULL
            AND rapid_outcome IS NULL
            AND product_disposition IS NULL
            AND error_category IS NULL
            AND source_sha IS NULL
            AND container_digest IS NULL
            AND job_definition_rev IS NULL
            AND config_digest IS NULL
            AND reconciliation_class IS NULL
            AND reconciliation_sources IS NULL
            AND reconciliation_detected_at IS NULL
        )
    ),

    -- Started: started_at, scheduler_job_id and all four provenance fields
    -- required; end/outcome/reconciliation absent.
    CONSTRAINT attempts_state_started_check CHECK (
        lifecycle_state <> 'started' OR (
            started_at IS NOT NULL
            AND scheduler_job_id IS NOT NULL
            AND source_sha IS NOT NULL
            AND container_digest IS NOT NULL
            AND job_definition_rev IS NOT NULL
            AND config_digest IS NOT NULL
            AND ended_at IS NULL
            AND process_exit_code IS NULL
            AND rapid_outcome IS NULL
            AND product_disposition IS NULL
            AND error_category IS NULL
            AND reconciliation_class IS NULL
            AND reconciliation_sources IS NULL
            AND reconciliation_detected_at IS NULL
        )
    ),

    -- Terminal after start: the started fields PLUS the end-state fields.
    -- Reconciliation absent — the row is resolved, not indeterminate.
    CONSTRAINT attempts_state_terminal_after_start_check CHECK (
        lifecycle_state <> 'terminal_after_start' OR (
            started_at IS NOT NULL
            AND scheduler_job_id IS NOT NULL
            AND source_sha IS NOT NULL
            AND container_digest IS NOT NULL
            AND job_definition_rev IS NOT NULL
            AND config_digest IS NOT NULL
            AND ended_at IS NOT NULL
            AND process_exit_code IS NOT NULL
            AND rapid_outcome IS NOT NULL
            AND product_disposition IS NOT NULL
            AND reconciliation_class IS NULL
            AND reconciliation_sources IS NULL
            AND reconciliation_detected_at IS NULL
        )
    ),

    -- Terminal without start: never ran. ended_at and scheduler_state required;
    -- all started-only fields absent, and product_disposition forbidden
    -- (amendment 1) — nothing ran, so nothing was produced to dispose of.
    CONSTRAINT attempts_state_terminal_without_start_check CHECK (
        lifecycle_state <> 'terminal_without_start' OR (
            ended_at IS NOT NULL
            AND scheduler_state IS NOT NULL
            AND started_at IS NULL
            AND process_exit_code IS NULL
            AND rapid_outcome IS NULL
            AND product_disposition IS NULL
            AND source_sha IS NULL
            AND container_digest IS NULL
            AND job_definition_rev IS NULL
            AND config_digest IS NULL
            AND reconciliation_class IS NULL
            AND reconciliation_sources IS NULL
            AND reconciliation_detected_at IS NULL
        )
    ),

    -- Missing or contradictory: the three reconciliation fields are required
    -- (reconciliation_sources included, per amendment 1). Which OTHER fields are
    -- absent is per-case, determined by what the observation could not
    -- establish — deliberately not fixed here, per § 4.
    CONSTRAINT attempts_state_missing_or_contradictory_check CHECK (
        lifecycle_state <> 'missing_or_contradictory' OR (
            reconciliation_class IS NOT NULL
            AND reconciliation_sources IS NOT NULL
            AND reconciliation_detected_at IS NOT NULL
        )
    )
);

CREATE INDEX IF NOT EXISTS attempts_run_idx ON attempts USING btree (run_id);
CREATE INDEX IF NOT EXISTS attempts_logical_job_idx ON attempts USING btree (logical_job_id);
CREATE INDEX IF NOT EXISTS attempts_scheduler_job_idx ON attempts USING btree (scheduler_job_id);
CREATE INDEX IF NOT EXISTS attempts_lifecycle_state_idx ON attempts USING btree (lifecycle_state);
CREATE INDEX IF NOT EXISTS attempts_exposure_sca_idx ON attempts USING btree (exposure_id, sca);

COMMENT ON TABLE attempts IS
    'One row per processing attempt, updated in place through its lifecycle. A '
    'retry is a new row with its own attempt_id, never an update to a prior '
    'attempt. Array-submitted children are independent rows created at '
    'submission time, before Batch assigns child identifiers.';
COMMENT ON COLUMN attempts.rapid_outcome IS
    'Application-level self-reported result. Deliberately distinct from '
    'scheduler_state: a Batch SUCCEEDED job can still carry rapid_outcome = '
    'failure (a stage failed but the process exited 0), which is exactly the '
    '2026-07-22 failure mode this field exists to expose.';
COMMENT ON COLUMN attempts.error_category IS
    'Machine-readable, allowlisted error class for a failed attempt (e.g. '
    'container_pull_error, oom, dependency_missing, science_failure). Allowlist '
    'is versioned with the schema; never free text.';
COMMENT ON COLUMN attempts.created_at IS
    'Logical-job creation time, application-authored. Start of the submission '
    'interval; submitted_at ends it.';
COMMENT ON COLUMN attempts.submitted_at IS
    'When the submitter issued the submission — NOT Batch acceptance. '
    'Application-authored.';
COMMENT ON COLUMN attempts.ended_at IS
    'Written by whichever party closes the attempt: the job at clean exit, the '
    'reconciler at classification for never-started and abrupt-loss attempts. '
    'Single-writer per row either way.';
COMMENT ON COLUMN attempts.scheduler_created_at IS
    'Batch createdAt, reconciler-written. For an array child this is child-spawn '
    'time (entry to PENDING), not array-call acceptance, so an '
    'application-vs-scheduler submission comparison includes normal spawn delay '
    'and its tolerance must absorb that.';
COMMENT ON COLUMN attempts.scheduler_started_at IS
    'Batch startedAt, reconciler-written. Never written by the application; '
    'disagreement with started_at is flagged by reconciliation, never '
    'overwritten.';
COMMENT ON COLUMN attempts.scheduler_stopped_at IS
    'Batch stoppedAt, reconciler-written.';
COMMENT ON COLUMN attempts.scheduler_attempt_index IS
    'Which Batch-level attempt of the job this row maps to. A scheduler retry '
    'keeps the Batch job ID, so the index is what distinguishes sibling rows'' '
    'scheduler evidence. Batch exposes no per-attempt creation or requeue time '
    '(AttemptDetail carries start/stop only), so the five-interval decomposition '
    'is fully defined only for a job''s first scheduler attempt; a retry''s queue '
    'interval is bounded only as prior-attempt stop -> this-attempt start.';
COMMENT ON COLUMN attempts.reconciliation_sources IS
    'Which stores were compared, e.g. {postgres,batch} or {postgres,batch,s3}.';

-- ---------------------------------------------------------------------------
-- attempt_stages — span-shaped, append-only: one row per stage execution,
-- written once at stage completion, never updated. Mechanically convertible to
-- OTel spans later without re-instrumentation.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attempt_stages (
    stage_record_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    attempt_id       bigint NOT NULL,
    stage_name       text NOT NULL,
    started_at       timestamptz NOT NULL,
    duration_ms      numeric NOT NULL,
    outcome          text NOT NULL,

    CONSTRAINT attempt_stages_pkey PRIMARY KEY (stage_record_id),
    CONSTRAINT attempt_stages_attempt_fk FOREIGN KEY (attempt_id)
        REFERENCES attempts(attempt_id),
    CONSTRAINT attempt_stages_duration_check CHECK (duration_ms >= 0),
    CONSTRAINT attempt_stages_outcome_check CHECK (outcome IN (
        'success', 'failure', 'skipped'
    ))
);

CREATE INDEX IF NOT EXISTS attempt_stages_attempt_idx ON attempt_stages USING btree (attempt_id);
CREATE INDEX IF NOT EXISTS attempt_stages_stage_name_idx ON attempt_stages USING btree (stage_name);

COMMENT ON COLUMN attempt_stages.duration_ms IS
    'Monotonic-clock duration in milliseconds (application-side timer, never '
    'wall-clock subtraction). Unit is fixed by the column name per the '
    'deliberate-schemas policy; no other unit is ever stored here.';
COMMENT ON COLUMN attempt_stages.started_at IS
    'UTC wall-clock start, for correlation and display only — duration_ms is '
    'authoritative for elapsed time, never derived from this column by '
    'subtraction against a later row.';
COMMENT ON COLUMN attempt_stages.stage_name IS
    'Drawn from a versioned, pipeline-owned vocabulary. Stages are flat within '
    'an attempt, ordered by started_at; there is no parent pointer.';

-- ---------------------------------------------------------------------------
-- milestones — named SCA-to-alert boundaries, append-only, independently
-- queryable per exposure/SCA/sky-tile. Deliberately NOT attempt-scoped as the
-- join key: a milestone is a fact about the processing unit, which may be
-- reached through more than one attempt across retries. The producing attempt
-- is recorded for traceability only.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS milestones (
    milestone_record_id  bigint GENERATED BY DEFAULT AS IDENTITY,
    milestone_name       text NOT NULL,
    exposure_id          integer,
    sca                  smallint,
    sky_tile             text,
    reached_at           timestamptz NOT NULL,
    producing_attempt_id bigint,

    CONSTRAINT milestones_pkey PRIMARY KEY (milestone_record_id),
    CONSTRAINT milestones_attempt_fk FOREIGN KEY (producing_attempt_id)
        REFERENCES attempts(attempt_id),
    CONSTRAINT milestones_scope_check CHECK (
        exposure_id IS NOT NULL OR sca IS NOT NULL OR sky_tile IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS milestones_name_idx ON milestones USING btree (milestone_name);
CREATE INDEX IF NOT EXISTS milestones_exposure_sca_idx ON milestones USING btree (exposure_id, sca);
CREATE INDEX IF NOT EXISTS milestones_sky_tile_idx ON milestones USING btree (sky_tile);

COMMENT ON COLUMN milestones.milestone_name IS
    'Named SCA-to-alert boundary (e.g. l2_ingested, differenced, '
    'catalog_generated, alert_published). Vocabulary is versioned with the '
    'schema, maintained alongside stage_name.';
COMMENT ON COLUMN milestones.producing_attempt_id IS
    'Traceability only — never the join key for milestone queries, because a '
    'processing unit may reach a milestone through more than one attempt.';

-- ---------------------------------------------------------------------------
-- attempt_record_schema_versions — producers and consumers declare which
-- versions they support (deliberate-schemas requirement). Written once per
-- schema change, not per row; attempts.schema_version references it informally
-- (no FK by design).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attempt_record_schema_versions (
    schema_version smallint NOT NULL,
    introduced_at  timestamptz NOT NULL DEFAULT now(),
    description    text NOT NULL,
    CONSTRAINT attempt_record_schema_versions_pkey PRIMARY KEY (schema_version)
);

INSERT INTO attempt_record_schema_versions (schema_version, description)
VALUES (1, 'Initial attempt-record schema: attempts, attempt_stages, '
           'milestones. Lifecycle matrix fully constraint-backed; '
           'application-authored and reconciler-written timestamp columns '
           'separated (both 2026-08-03 amendments folded in before first apply).')
ON CONFLICT (schema_version) DO NOTHING;
