"""Fake external tools for the difference stage, and a synthetic input set.

``FakeToolRunner`` stands in for :class:`rapidpipe.science.difference.tools.ToolRunner`:
it recognises each command the stage issues (SExtractor ``sex``, SWarp
``swarp``, ``bkgest``, ``py_zogy.py``, and the SFFT shell command) and
writes plausible outputs with numpy and astropy, so the whole stage can
run with no C tools, no ZOGY and no SFFT installed. The outputs are not
the tools' science; they are shaped like it (same files, same headers,
same catalog columns), which is what the stage's own logic needs. Every
call is recorded for assertions.

``fake_psf_catalog`` stands in for
:func:`rapidpipe.science.difference.psfcat.psf_catalog` (photutils).

``build_input_set`` writes a small synthetic input set -- a two-HDU
science image with a SIP WCS, a reference bundle on the same sky, the
reference catalog, two PSFs -- and its input-set manifest. The fixture
under ``tests/fixtures/difference/`` (and its packaged copy,
``rapidpipe/selftest/fixtures/difference/``, read by ``rapidpipe
selftest``) is generated by the same function.

Packaged under ``rapidpipe.selftest.support`` (not ``tests/``, which the
pipeline image excludes at build time -- ``containers/rapid-pipeline/
build.sh``) so ``rapidpipe selftest --stage difference`` can import it
inside the image. ``tests/unit/fakedifftools.py`` re-exports this module
for the test suite and for ``RAPIDPIPE_DIFFERENCE_TOOLKIT=tests.unit.
fakedifftools:fake_toolkit``.
"""

from __future__ import annotations

import hashlib
import json
import shlex
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
from astropy.io import fits

from rapidpipe.science.difference.psfcat import PsfCatalogResult

REPO_ROOT = Path(__file__).resolve().parents[3]
#: The repository's own SExtractor parameter files; tests point the
#: stage's [paths] cfg_path here, where production uses /code/cdf.
CDF_DIR = REPO_ROOT / "cdf"

NAXIS = 64
PIXEL_SCALE_DEG = 0.11 / 3600.0
CRVAL = (269.4521, -28.7710)
EXPTIME = 140.0
ZPTMAG = 17.0
STARS = ((20.0, 22.0, 4000.0), (40.0, 18.0, 2500.0), (30.0, 44.0, 6000.0), (50.0, 50.0, 3000.0))
TRANSIENT = (12.0, 40.0, 3500.0)   # in the science image only


def _gaussian(n: int, x0: float, y0: float, sigma: float = 1.2) -> np.ndarray:
    yy, xx = np.mgrid[0:n, 0:n]
    return np.exp(-(((xx - x0) ** 2) + ((yy - y0) ** 2)) / (2 * sigma ** 2))


def wcs_header(naxis: int, *, sip: bool) -> fits.Header:
    h = fits.Header()
    h["CTYPE1"] = "RA---TAN-SIP" if sip else "RA---TAN"
    h["CTYPE2"] = "DEC--TAN-SIP" if sip else "DEC--TAN"
    h["CRVAL1"], h["CRVAL2"] = CRVAL
    h["CRPIX1"] = naxis / 2.0
    h["CRPIX2"] = naxis / 2.0
    h["CD1_1"] = -PIXEL_SCALE_DEG
    h["CD1_2"] = 0.0
    h["CD2_1"] = 0.0
    h["CD2_2"] = PIXEL_SCALE_DEG
    h["CUNIT1"] = "deg"
    h["CUNIT2"] = "deg"
    if sip:
        h["A_ORDER"] = 2
        h["A_2_0"] = 1.0e-7
        h["B_ORDER"] = 2
        h["B_0_2"] = 1.0e-7
    return h


def _sky(n: int, stars, rng, *, background: float, noise: float) -> np.ndarray:
    data = rng.normal(background, noise, size=(n, n))
    for x0, y0, flux in stars:
        data += flux * _gaussian(n, x0, y0) / (2 * np.pi * 1.2 ** 2)
    return data


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _member(role: str, path: Path, base: Path) -> dict:
    return {"role": role, "path": path.relative_to(base).as_posix(),
            "bytes": path.stat().st_size, "sha256": _sha256(path)}


def _l2_registration(infobits: int = 0) -> dict:
    return {
        "exposure_id": "e20260821001234", "detector": 7, "delivered_version": "1",
        "filter": "F184", "dateobs": "2026-08-21T00:12:34", "mjdobs": 61273.0087,
        "exptime": EXPTIME, "infobits": infobits, "status": 1,
        "naxis1": NAXIS, "naxis2": NAXIS,
        "crval1": CRVAL[0], "crval2": CRVAL[1], "crpix1": NAXIS / 2.0, "crpix2": NAXIS / 2.0,
        "cd11": -PIXEL_SCALE_DEG, "cd12": 0.0, "cd21": 0.0, "cd22": PIXEL_SCALE_DEG,
        "ctype1": "RA---TAN-SIP", "ctype2": "DEC--TAN-SIP", "cunit1": "deg", "cunit2": "deg",
        "equinox": 2000.0, "a_order": 2, "a": {"2_0": 1.0e-7}, "b_order": 2, "b": {"0_2": 1.0e-7},
        "ra_targ": CRVAL[0], "dec_targ": CRVAL[1], "pa_obsy": None, "pa_fpa": None,
        "zptmag": ZPTMAG, "skymean": None,
        "centre": {"ra": 269.4521, "dec": -28.7710},
        "corners": [[269.4526, -28.7720], [269.4516, -28.7720],
                    [269.4516, -28.7700], [269.4526, -28.7700]],
        "md5": "9e107d9d372bb6826bd81d3542a419d6", "hdu": 1,
        "delivery_instance": "01ARZ3NDEKTSV4RRFFQ69G5FAV", "delivery_source": "synthetic",
    }


L2_INSTANCE = "01J8Y6QZ3MA2B4C6D8E0F2G2AA"
REF_INSTANCE = "01J8Y6QZ3MA2B4C6D8E0F2G2RF"
REFCAT_INSTANCE = "01J8Y6QZ3MA2B4C6D8E0F2G2RC"
SCI_PSF_INSTANCE = "01J8Y6QZ3MA2B4C6D8E0F2G2PS"
REF_PSF_INSTANCE = "01J8Y6QZ3MA2B4C6D8E0F2G2PR"

SCIENCE_NAME = "Roman_WAS_simple_model_F184_1234_7.fits.gz"


def build_input_set(inputs_dir: Path, *, seed: int = 20260922, rfid: int | None = None,
                    ref_infobits: int = 0, gzip_science: bool = True) -> Path:
    """Write the synthetic inputs and their input-set manifest; return the manifest path."""
    rng = np.random.default_rng(seed)
    inputs_dir.mkdir(parents=True, exist_ok=True)
    (inputs_dir / "l2").mkdir(exist_ok=True)
    (inputs_dir / "ref").mkdir(exist_ok=True)
    (inputs_dir / "psf").mkdir(exist_ok=True)

    # Science: DN in HDU 1, 64x64, dev's socsims layout.
    sci = _sky(NAXIS, STARS + (TRANSIENT,), rng, background=100.0 * EXPTIME / 10, noise=5.0)
    sci_header = wcs_header(NAXIS, sip=True)
    sci_header["EXPTIME"] = EXPTIME
    sci_header["ZPTMAG"] = ZPTMAG
    sci_header["SCA-NUM"] = 7
    science_path = inputs_dir / "l2" / (SCIENCE_NAME if gzip_science else SCIENCE_NAME[:-3])
    fits.HDUList([fits.PrimaryHDU(), fits.ImageHDU(data=sci.astype(np.float32),
                                                   header=sci_header)]).writeto(science_path)

    # Reference bundle on the 65x65 grid the reformatted science image has.
    n = NAXIS + 1
    # DN/s, the science stars without the transient.
    ref = _sky(n, tuple((x, y, f / EXPTIME) for x, y, f in STARS), rng, background=0.0, noise=0.02)
    ref_header = wcs_header(n, sip=False)
    ref_header["MAGZP"] = 17.0
    ref_image = inputs_dir / "ref" / "awaicgen_output_mosaic_image.fits"
    fits.PrimaryHDU(data=ref.astype(np.float32), header=ref_header).writeto(ref_image)
    ref_cov = inputs_dir / "ref" / "awaicgen_output_mosaic_cov_map.fits"
    cov = np.full((n, n), 5.0, dtype=np.float32)
    cov[:, :3] = 0.0            # an uncovered strip the coverage mask must blank
    fits.PrimaryHDU(data=cov, header=ref_header).writeto(ref_cov)
    ref_unc = inputs_dir / "ref" / "awaicgen_output_mosaic_uncert_image.fits"
    fits.PrimaryHDU(data=np.full((n, n), 0.02, dtype=np.float32), header=ref_header).writeto(ref_unc)
    ref_cat = inputs_dir / "ref" / "awaicgen_output_mosaic_refimsexcat.txt"
    params = _params(str(CDF_DIR / "rapidSexParamsRefImage.inp"))
    ref_cat.write_text(
        "".join(f"#{i + 1:4d} {p}\n" for i, p in enumerate(params))
        + "".join(" ".join(_catalog_row(p, int(x), int(y), flux) for p in params) + "\n"
                  for x, y, flux in STARS))

    # PSFs: 9x9 Gaussians.
    sci_psf = inputs_dir / "psf" / "sciimage_psf_f184_sca07.fits"
    fits.PrimaryHDU(data=(3.0 * _gaussian(9, 4, 4)).astype(np.float32)).writeto(sci_psf)
    ref_psf = inputs_dir / "psf" / "refimage_psf_f146_sca07.fits"
    psf = _gaussian(9, 4, 4)
    fits.PrimaryHDU(data=(psf / psf.sum()).astype(np.float32)).writeto(ref_psf)

    manifest = {
        "schema_version": "1",
        "run": "01J8Y6QZ3MA2B4C6D8E0F2G2RN",
        "unit": {"kind": "detector-image", "id": "e20260821001234/SCA07"},
        "stage": "input-set",
        "attempt": "01J8Y6QZ3MA2B4C6D8E0F2G2AT",
        "execution_record": "exec/input-set.json",
        "inputs": {"manifest": "input-set", "products": {}, "result_sets": []},
        "outputs": [
            {"kind": "l2-image", "format_version": "1", "instance": L2_INSTANCE,
             "key": {"exposure": "e20260821001234", "detector": "7", "version": "1"},
             "primary": _member("image", science_path, inputs_dir)["path"],
             "members": [_member("image", science_path, inputs_dir)],
             "registration": _l2_registration()},
            {"kind": "reference-image", "format_version": "1", "instance": REF_INSTANCE,
             "key": {"field": "5321", "filter": "F184", "recipe": "awaicgen", "version": "1"},
             "primary": _member("image", ref_image, inputs_dir)["path"],
             "members": [_member("image", ref_image, inputs_dir),
                         _member("coverage", ref_cov, inputs_dir),
                         _member("uncertainty", ref_unc, inputs_dir)],
             "registration": {"infobits": ref_infobits, "rfid": rfid}},
            {"kind": "reference-catalog", "format_version": "1", "instance": REFCAT_INSTANCE,
             "key": {"reference": REF_INSTANCE, "catalog_type": "sextractor"},
             "primary": _member("catalog", ref_cat, inputs_dir)["path"],
             "members": [_member("catalog", ref_cat, inputs_dir)], "registration": {}},
            {"kind": "psf", "format_version": "1", "instance": SCI_PSF_INSTANCE,
             "key": {"filter": "F184", "detector": "7", "version": "1", "applies_to": "science"},
             "primary": _member("psf", sci_psf, inputs_dir)["path"],
             "members": [_member("psf", sci_psf, inputs_dir)], "registration": {}},
            {"kind": "psf", "format_version": "1", "instance": REF_PSF_INSTANCE,
             "key": {"filter": "F184", "detector": "7", "version": "1", "applies_to": "reference"},
             "primary": _member("psf", ref_psf, inputs_dir)["path"],
             "members": [_member("psf", ref_psf, inputs_dir)], "registration": {}},
        ],
    }
    if gzip_science:
        import gzip
        raw = science_path.read_bytes()
        science_path.write_bytes(gzip.compress(raw, mtime=0))
        manifest["outputs"][0]["members"] = [_member("image", science_path, inputs_dir)]
    manifest_path = inputs_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest_path


# ----------------------------------------------------------------------
# The fake runner
# ----------------------------------------------------------------------


def _option(args: list[str], name: str) -> str:
    return args[args.index(name) + 1]


def _read(path: Path) -> tuple[np.ndarray, fits.Header]:
    with fits.open(path) as hdul:
        return np.array(hdul[0].data, dtype=np.float64), hdul[0].header.copy()


def _params(params_file: str) -> list[str]:
    return [line.strip() for line in Path(params_file).read_text().splitlines() if line.strip()]


def _peaks(data: np.ndarray, nsigma: float = 5.0) -> list[tuple[int, int, float]]:
    finite = np.isfinite(data)
    if not finite.any():
        return []
    med = np.nanmedian(data)
    sigma = np.nanstd(data[finite]) or 1.0
    peaks = []
    n0, n1 = data.shape
    for i in range(2, n0 - 2):
        for j in range(2, n1 - 2):
            v = data[i, j]
            if not np.isfinite(v) or v < med + nsigma * sigma:
                continue
            box = data[i - 1:i + 2, j - 1:j + 2]
            if v >= np.nanmax(box):
                peaks.append((j, i, float(np.nansum(data[i - 2:i + 3, j - 2:j + 3]))))
    return peaks


def _catalog_row(param: str, x: int, y: int, flux: float) -> str:
    base = param.split("(")[0]
    values = {
        "XWIN_IMAGE": x + 1.0, "YWIN_IMAGE": y + 1.0, "X_IMAGE": x + 1.0, "Y_IMAGE": y + 1.0,
        "FLUX_APER": flux, "MAG_APER": -2.5 * np.log10(abs(flux)) if flux else 99.0,
        "CLASS_STAR": 0.9, "ISOAREAF_IMAGE": 12.0, "AWIN_WORLD": 1.0e-5, "BWIN_WORLD": 1.0e-5,
        "FWHM_IMAGE": 2.4,
    }
    return f"{values.get(base, 0.0):.6f}"


@dataclass
class FakeToolRunner:
    """Recognises the difference stage's commands and fakes their outputs."""

    sfft_exit_code: int = 0
    calls: list[list[str]] = field(default_factory=list)
    shell_calls: list[str] = field(default_factory=list)

    def tools_called(self) -> list[str]:
        names = []
        for args in self.calls:
            if args[0].endswith("sex"):
                names.append("sextractor")
            elif args[0].endswith("swarp"):
                names.append("swarp")
            elif args[0].endswith("bkgest"):
                names.append("bkgest")
            elif len(args) > 1 and args[1].endswith("py_zogy.py"):
                names.append("zogy")
            else:
                names.append(args[0])
        return names + ["sfft"] * len(self.shell_calls)

    def run(self, args, *, cwd: Path) -> int:
        args = [str(a) for a in args]
        self.calls.append(args)
        cwd = Path(cwd)
        if args[0].endswith("sex"):
            self._sextractor(args, cwd)
        elif args[0].endswith("swarp"):
            self._swarp(args, cwd)
        elif args[0].endswith("bkgest"):
            self._bkgest(args, cwd)
        elif len(args) > 1 and args[1].endswith("py_zogy.py"):
            self._zogy(args, cwd)
        else:
            raise AssertionError(f"unexpected tool call {args!r}")
        return 0

    def run_shell(self, command: str, *, cwd: Path) -> int:
        self.shell_calls.append(command)
        if self.sfft_exit_code != 0:
            return self.sfft_exit_code
        # No activation: the whole command is the sfft call. With
        # activation, dev's "source ... && <sfft cmd> && deactivate".
        parts = command.split(" && ")
        sfft_call = parts[1] if len(parts) > 1 else parts[0]
        tokens = shlex.split(sfft_call)
        sci, ref = tokens[2].removeprefix("./"), tokens[3].removeprefix("./")
        sci_data, header = _read(Path(cwd) / sci)
        ref_data, _ = _read(Path(cwd) / ref)
        crossconv = "--crossconv" in tokens
        diff = "sfftdiffimage_dconv_masked.fits" if crossconv else "sfftdiffimage_masked.fits"
        fits.PrimaryHDU(data=(sci_data - ref_data).astype(np.float32), header=header).writeto(
            Path(cwd) / diff, overwrite=True)
        soln = "sfftsoln_cconv.fits" if crossconv else "sfftsoln.fits"
        fits.PrimaryHDU(data=np.ones((3, 3), dtype=np.float32)).writeto(Path(cwd) / soln, overwrite=True)
        psf_name = "sfftdiffpsf_dconv.fits" if crossconv else "sfftdiffpsf.fits"
        psf_data, _ = _read(Path(cwd) / tokens[tokens.index("--scipsf") + 1])
        fits.PrimaryHDU(data=psf_data.astype(np.float32)).writeto(Path(cwd) / psf_name, overwrite=True)
        return 0

    # -- the tools --

    def _sextractor(self, args, cwd: Path) -> None:
        images = args[1].split(",")
        detection = images[0]
        data, _ = _read(cwd / detection)
        params = _params(_option(args, "-PARAMETERS_NAME"))
        lines = [f"#{i + 1:4d} {p}\n" for i, p in enumerate(params)]
        for x, y, flux in _peaks(data):
            lines.append(" ".join(_catalog_row(p, x, y, flux) for p in params) + "\n")
        (cwd / _option(args, "-CATALOG_NAME")).write_text("".join(lines))

    def _swarp(self, args, cwd: Path) -> None:
        source, _ = _read(cwd / args[1])
        output = _option(args, "-IMAGEOUT_NAME")
        grid_header = fits.getheader(cwd / output.replace(".fits", ".head"))
        n1, n2 = grid_header["NAXIS1"], grid_header["NAXIS2"]
        resampled = np.zeros((n2, n1))
        m2, m1 = min(n2, source.shape[0]), min(n1, source.shape[1])
        resampled[:m2, :m1] = source[:m2, :m1]
        if _option(args, "-SUBTRACT_BACK") == "Y":
            resampled -= np.median(resampled)
        header = grid_header.copy()
        fits.PrimaryHDU(data=resampled.astype(np.float32), header=header).writeto(
            cwd / output, overwrite=True)
        fits.PrimaryHDU(data=np.ones((n2, n1), dtype=np.float32)).writeto(
            cwd / _option(args, "-WEIGHTOUT_NAME"), overwrite=True)

    def _bkgest(self, args, cwd: Path) -> None:
        data, header = _read(cwd / _option(args, "-i"))
        fits.PrimaryHDU(data=(data - np.nanmedian(data)).astype(np.float32), header=header).writeto(
            cwd / _option(args, "-o2"), overwrite=True)
        (cwd / _option(args, "-ot")).write_text(f"clippedmean {np.nanmedian(data)}\n")

    def _zogy(self, args, cwd: Path) -> None:
        (new, ref, new_psf, _ref_psf, new_sigma, ref_sigma,
         _sn, _sr, _dx, _dy, diff, diff_psf, scorr) = args[2:15]
        new_data, header = _read(cwd / new)
        ref_data, _ = _read(cwd / ref)
        sig_new, _ = _read(cwd / new_sigma)
        sig_ref, _ = _read(cwd / ref_sigma)
        d = new_data - ref_data
        fits.PrimaryHDU(data=d.astype(np.float32), header=header).writeto(cwd / diff, overwrite=True)
        s = d / np.sqrt(sig_new ** 2 + sig_ref ** 2)
        fits.PrimaryHDU(data=s.astype(np.float32), header=header).writeto(cwd / scorr, overwrite=True)
        psf_data, _ = _read(cwd / new_psf)
        fits.PrimaryHDU(data=psf_data.astype(np.float32)).writeto(cwd / diff_psf, overwrite=True)


def fake_sip_to_pv(header) -> None:
    """Stands in for the vendored SIP-to-PV converter (which needs sympy)."""
    for key in [k for k in header if k.startswith(("A_", "B_", "AP_", "BP_"))]:
        del header[key]
    header["CTYPE1"] = "RA---TPV"
    header["CTYPE2"] = "DEC--TPV"


@dataclass
class FakePsfCatalog:
    """Stands in for ``psfcat.psf_catalog``; ``fail`` lists labels to fail."""

    fail: tuple[str, ...] = ()
    calls: list[dict[str, Any]] = field(default_factory=list)

    def __call__(self, settings, **kwargs) -> PsfCatalogResult:
        self.calls.append(kwargs)
        if kwargs["label"] in self.fail:
            return PsfCatalogResult(produced=False, nsources=None)
        data, _ = _read(Path(kwargs["image"]))
        nsources = len(_peaks(data))
        Path(kwargs["catalog"]).write_text(f"# id x_fit y_fit\n# {nsources} sources\n")
        Path(kwargs["finder"]).write_text("# finder\n")
        return PsfCatalogResult(produced=True, nsources=nsources)


def fake_toolkit():
    """Every external tool faked: the value ``RAPIDPIPE_DIFFERENCE_TOOLKIT`` names
    (``tests.unit.fakedifftools:fake_toolkit``) for a stage run as a subprocess."""
    from rapidpipe.stages.difference import Toolkit

    return Toolkit(runner=FakeToolRunner(), sip_to_pv=fake_sip_to_pv, psf_catalog=FakePsfCatalog())
